version: "3"

services:
  # management: http://localhost:15672
  rabbitmq:
    image: miyako-rabbitmq
    ports:
      - 1883:1883
      - 5672:5672
      - 15672:15672
      - 15675:15675
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest