version: "3"

services:
  # management: http://localhost:15672
  rabbitmq:
    image: miyako-rabbitmq
    ports:
      - 1883:1883 # mqtt
      - 5672:5672 # amqp
      - 15672:15672  # http (management)
      - 15674:15674  # http/web-stomp
      - 15675:15675  # http/web-mqtt
      - 25672:25672  # clustering
      - 61613:61613  # stomp
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
